### ISSUE TITLE
C_read Directory of Files

### ISSUE THREAD

**Issue by DeviPriya-Kolla** [oss-slu/tbe#50]
**Description:** 
Develop functionality to process an entire directory of TBE files in C, loading and parsing each file sequentially. This will facilitate batch processing, allowing users to aggregate metadata and handle errors efficiently across multiple files.

**Developer Notes:**
- Implement a function that iterates through all files in a specified directory, selecting only TBE files for processing.
- The function should return parsed data in a structured format (e.g., an array of structs) that is easily accessible and usable for further operations.
- Provide options for generating summary reports by aggregating key metadata fields across all processed TBE files.

**Acceptance Criteria:**
- [x] Functionality to read all TBE files in a directory
- [x]  metadata aggregation
- [x]  skip each non-TBE files and log a warning
- [x]  provide logging or progress updates
- [x]  an option to return summary metadata in a JSON or visual format

**Comment by BaloneyBoy97** [comment]
I would like to tackle this issue @DeviPriya-Kolla. I will try to make functionality to read all TBE files in a directory.
